# Generated by Django 5.2.5 on 2025-09-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examtype',
            options={'ordering': ['name']},
        ),
    ]
